#!/bin/sh
#
# Execute two main test to avoid excessive CircleCi usage

echo "########################################################"
echo "############  Decidim pre-push validation   ############"
echo "You can bypass this hook with the --no-verify or -n flag"
echo "########################################################"

bundle exec rake test_core
bundle exec rake test_app
