version: '2'
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-60
    checks:
      Rubocop/Style/ClassAndModuleChildren:
        enabled: false
      Rubocop/Layout/IndentHeredoc:
        enabled: false
      Rubocop/Style/Lambda:
        enabled: false
      Rubocop/Bundler/OrderedGems:
        enabled: false

  eslint:
    enabled: true
    checks:
      jsx-a11y/anchor-is-valid:
        enabled: false
exclude_patterns:
  - 'config/'
  - 'db/'
  - 'dist/'
  - 'features/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - '**/__test__/'
  - '**/*.test.js'
  - '**/vendor/'
  - '**/*.d.ts'
  - 'app/assets/javascripts/**'
  - 'config/webpack/**'
  - 'spec/javascripts/**'
  - 'doc/'
  - 'bin/'
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: true
  identical-code:
    enabled: true
