require "decidim/extends/notification_mailer_extend.rb"
require "decidim/extends/commands/create_omniauth_registration_extend.rb"
require "decidim/extends/forms/omniauth_registration_form_extend.rb"
require "decidim/extends/models/user_extend.rb"
require "decidim/extends/controllers/omniauth_registrations_controller_extend.rb"
